### ISSUE TITLE
cocos 3.6 problem with this example

### ISSUE THREAD

**Issue by nazrdogan** [SonarSystems/Cocos2d-JS-v3-Tutorial-32---Stopping-Sound-Effects#1]
I m very new cocos2d-js . I tried this example but .its give me

<code>
16:37:19 Starting simulator...
16:37:20 Start LaunchActivity org.cocos2dx.PrebuiltRuntimeJs/org.cocos2dx.javascript.AppActivity
16:37:22 Uploading resources ...
16:37:22 Uploading resources ...
16:37:23 cocos2d: fullPathForFilename: No file found at script/jsb_boot.jsc. Possible missing file.
16:37:23 create rendererRecreatedListener for GLProgramState
16:37:24 jsb: ERROR: File /Users/hejialin/IdeaProjects/eclipse/PrebuiltRuntimeJs/frameworks/runtime-src/proj.android/../../js-bindings/bindings/auto/jsb_cocos2dx_auto.cpp: Line: 5173, Function: js_cocos2dx_Node_setTag
16:37:24 js_cocos2dx_Node_setTag : Invalid Native Object
16:37:24 (evaluatedOK == JS_FALSE)
16:37:24 JS: /data/data/org.cocos2dx.PrebuiltRuntimeJs/files/debugruntime/script/jsb_cocos2d.js:1389:Error: js_cocos2dx_Node_setTag : Invalid Native Object
16:37:24 (evaluatedOK == JS_FALSE)
</code>

**Comment by SonarSystems** [comment]
Does a fresh project work.

**Comment by nazrdogan** [comment]
yes its a fresh project. I just copy  app.js and resources files

**Comment by SonarSystems** [comment]
But does a freshly generated project work without these files.

**Comment by nazrdogan** [comment]
I dont know .I m using Intellij Plugin for development. Maybe its caching something. I m following your tutorial .only these one not works. fresh project works well but when  I add your code for stopping effects .its break.

**Comment by SonarSystems** [comment]
What version of Cocos2d-JS are you using?

**Comment by nazrdogan** [comment]
I m using cocos2d-js 3.6

**Comment by SonarSystems** [comment]
Try v3

**Comment by nazrdogan** [comment]
its not stable version ?

**Comment by SonarSystems** [comment]
Should be ok but just to make sure nothing has changed.
